stages:
  - Benchmark

cache:
  paths:
  - apt-cache/

benchmark_llvm:
  image: registry.gitlab.com/rirvm/rir_mirror:master
  stage: Benchmark
  tags:
    - benchmarks
  script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq python3-pip sudo
    - git clone --depth 1 https://github.com/smarr/ReBench.git /opt/ReBench && cd /opt/ReBench && pip3 install .
    - git clone --depth 10 https://github.com/reactorlabs/rbenchmarking /opt/rbenchmarking && cd /opt/rbenchmarking && git checkout 5977a8ab19d193eb4be262cdcd3ba375e5d436fd
    - cd $CI_PROJECT_DIR
    - cp -r experiment /opt/
    - rebench experiment/rebench.conf
  artifacts:
    paths:
    - benchmarks.data
    expire_in: 24 month
  retry: 1
